version: '3'
services:
  solr:
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    image: bireme/solr:5.5.5
    ports:
         - "${CONTAINER_PORT}:8983"
    env_file:
      - .env
    user: "${USER_GROUP_IDS}"
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
    networks:
      - nginx-proxy
    volumes:
      - ./solr_indexes:/opt/solr/server/solr/mycores

networks:
  nginx-proxy:
    external: true
